-- ==========================================
-- CODE SIXTY-FOUR: MASTER DATABASE SCHEMA
-- ==========================================

-- ------------------------------------------
-- 1. EXTENSIONS
-- ------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------
-- 2. TABLE CREATION
-- ------------------------------------------

CREATE TABLE public.profiles (
  id UUID NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.leagues (
  id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
  name TEXT NOT NULL,
  created_by UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  invite_code TEXT UNIQUE,
  status TEXT DEFAULT 'pre_draft'::TEXT,
  current_pick INTEGER DEFAULT 1,
  max_members INTEGER DEFAULT 8,
  season_year INTEGER DEFAULT 2026,
  member_count INTEGER DEFAULT 0,
  CONSTRAINT leagues_pkey PRIMARY KEY (id),
  CONSTRAINT leagues_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles (id),
  CONSTRAINT leagues_status_check CHECK (status IN ('pre_draft', 'drafting', 'in_progress', 'completed'))
) TABLESPACE pg_default;

CREATE TABLE public.league_members (
  league_id UUID NOT NULL,
  user_id UUID NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  draft_position INTEGER,
  CONSTRAINT league_members_pkey PRIMARY KEY (league_id, user_id),
  CONSTRAINT league_members_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues (id) ON DELETE CASCADE,
  CONSTRAINT league_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.teams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NOT NULL,
  seed INTEGER NOT NULL,
  region TEXT NOT NULL,
  wins INTEGER DEFAULT 0,
  is_eliminated BOOLEAN DEFAULT FALSE,
  season_year INTEGER DEFAULT 2026,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_seed_check CHECK (seed >= 1 AND seed <= 16)
) TABLESPACE pg_default;

CREATE TABLE public.games (
  id INTEGER NOT NULL,
  round INTEGER NOT NULL,
  team1_id INTEGER,
  team2_id INTEGER,
  winner_id INTEGER,
  next_game_id INTEGER,
  team1_score INTEGER,
  team2_score INTEGER,
  is_completed BOOLEAN DEFAULT FALSE,
  season_year INTEGER DEFAULT 2026,
  CONSTRAINT games_pkey PRIMARY KEY (id),
  CONSTRAINT games_next_game_id_fkey FOREIGN KEY (next_game_id) REFERENCES games (id),
  CONSTRAINT games_team1_id_fkey FOREIGN KEY (team1_id) REFERENCES teams (id),
  CONSTRAINT games_team2_id_fkey FOREIGN KEY (team2_id) REFERENCES teams (id),
  CONSTRAINT games_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES teams (id),
  CONSTRAINT games_round_check CHECK (round >= 1 AND round <= 6)
) TABLESPACE pg_default;

CREATE TABLE public.draft_picks (
  id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
  league_id UUID NOT NULL,
  user_id UUID NOT NULL,
  team_id INTEGER NOT NULL,
  drafted_at TIMESTAMPTZ DEFAULT NOW(),
  pick_number INTEGER,
  CONSTRAINT draft_picks_pkey PRIMARY KEY (id),
  CONSTRAINT draft_picks_league_id_team_id_key UNIQUE (league_id, team_id),
  CONSTRAINT draft_picks_league_id_fkey FOREIGN KEY (league_id) REFERENCES leagues (id) ON DELETE CASCADE,
  CONSTRAINT draft_picks_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams (id),
  CONSTRAINT draft_picks_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ------------------------------------------
-- 3. FUNCTIONS & TRIGGERS
-- ------------------------------------------

-- Auto-create user profile on sign up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, SPLIT_PART(NEW.email, '@', 1));
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Enforce League Member Capacity
CREATE OR REPLACE FUNCTION public.check_league_capacity() 
RETURNS TRIGGER AS $$
BEGIN
  IF (SELECT COUNT(*) FROM public.league_members WHERE league_id = NEW.league_id) >= 
     (SELECT max_members FROM public.leagues WHERE id = NEW.league_id) THEN
    RAISE EXCEPTION 'League has reached its maximum capacity';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_max_members
  BEFORE INSERT ON public.league_members
  FOR EACH ROW EXECUTE FUNCTION public.check_league_capacity();

-- Keep League Member Count Synced
CREATE OR REPLACE FUNCTION public.update_league_member_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.leagues SET member_count = member_count + 1 WHERE id = NEW.league_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.leagues SET member_count = member_count - 1 WHERE id = OLD.league_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_league_member_count
  AFTER INSERT OR DELETE ON public.league_members
  FOR EACH ROW EXECUTE FUNCTION public.update_league_member_count();

-- ------------------------------------------
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.league_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.draft_picks ENABLE ROW LEVEL SECURITY;

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- Leagues
CREATE POLICY "Authenticated users can view leagues" ON public.leagues FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can create leagues" ON public.leagues FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "Allow updates to leagues" ON public.leagues FOR UPDATE TO authenticated USING (true);

-- League Members
CREATE POLICY "Users can view their league memberships" ON public.league_members FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can join a league" ON public.league_members FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Commissioners can update members" ON public.league_members FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM public.leagues WHERE leagues.id = league_members.league_id AND leagues.created_by = auth.uid())
);

-- Teams & Games
CREATE POLICY "Allow public read access to teams" ON public.teams FOR SELECT USING (true);
CREATE POLICY "Allow public read access to games" ON public.games FOR SELECT USING (true);
CREATE POLICY "Allow public updates to games" ON public.games FOR UPDATE USING (true);

-- Draft Picks
CREATE POLICY "Allow read draft picks" ON public.draft_picks FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow public insert to draft_picks" ON public.draft_picks FOR INSERT WITH CHECK (true);

-- ------------------------------------------
-- 5. REALTIME SUBSCRIPTIONS
-- ------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE public.leagues;
ALTER PUBLICATION supabase_realtime ADD TABLE public.draft_picks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.teams;

-- ------------------------------------------
-- 6. DATA SEEDING (TEAMS & BRACKET)
-- ------------------------------------------

-- Populate 64 Tournament Teams
DO $$
DECLARE
    r TEXT;
    s INT;
    team_id INT := 1;
    regions TEXT[] := ARRAY['East', 'West', 'South', 'Midwest'];
BEGIN
    FOREACH r IN ARRAY regions LOOP
        FOR s IN 1..16 LOOP
            INSERT INTO public.teams (id, name, seed, region, season_year)
            VALUES (team_id, r || ' Seed ' || s, s, r, 2026);
            team_id := team_id + 1;
        END LOOP;
    END LOOP;
END $$;

-- Generate 63 Games & Round 1 Matchups
DO $$
DECLARE
    g INT;
    next_g INT;
    r INT;
    team_offset INT;
    matchups INT[] := ARRAY[1, 16, 8, 9, 5, 12, 4, 13, 6, 11, 3, 14, 7, 10, 2, 15];
BEGIN
    -- 1. Insert Round 1: Games 1-32
    FOR g IN 1..32 LOOP
        next_g := 32 + CEIL(g / 2.0);
        r := FLOOR((g - 1) / 8);
        team_offset := r * 16;
        
        INSERT INTO public.games (id, round, next_game_id, team1_id, team2_id, season_year) 
        VALUES (
            g, 1, next_g, 
            team_offset + matchups[(((g - 1) % 8 + 1) * 2) - 1], 
            team_offset + matchups[((g - 1) % 8 + 1) * 2],
            2026
        );
    END LOOP;

    -- 2. Insert Round 2: Games 33-48
    FOR g IN 33..48 LOOP
        next_g := 48 + CEIL((g - 32) / 2.0);
        INSERT INTO public.games (id, round, next_game_id, season_year) VALUES (g, 2, next_g, 2026);
    END LOOP;

    -- 3. Insert Round 3 (Sweet 16): Games 49-56
    FOR g IN 49..56 LOOP
        next_g := 56 + CEIL((g - 48) / 2.0);
        INSERT INTO public.games (id, round, next_game_id, season_year) VALUES (g, 3, next_g, 2026);
    END LOOP;

    -- 4. Insert Round 4 (Elite 8): Games 57-60
    FOR g IN 57..60 LOOP
        next_g := 60 + CEIL((g - 56) / 2.0);
        INSERT INTO public.games (id, round, next_game_id, season_year) VALUES (g, 4, next_g, 2026);
    END LOOP;

    -- 5. Insert Round 5 (Final 4): Games 61-62
    FOR g IN 61..62 LOOP
        INSERT INTO public.games (id, round, next_game_id, season_year) VALUES (g, 5, 63, 2026);
    END LOOP;

    -- 6. Insert Round 6 (Championship): Game 63
    INSERT INTO public.games (id, round, next_game_id, season_year) VALUES (63, 6, NULL, 2026);
END $$;